// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    print("check platform");
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBozy3Ed602xf28hKfE4txeHfJh6-Y0H6Q',
    appId: '1:234885058276:android:5ad80d7880eb466e4826f1',
    messagingSenderId: '234885058276',
    projectId: 'video-plus-256c2',
    storageBucket: 'video-plus-256c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzKOvuJVkAQ5hbxJxr0M2tmoHiAegVJE',
    appId: '1:234885058276:ios:b24f6f7d570e49a64826f1',
    messagingSenderId: '234885058276',
    projectId: 'video-plus-256c2',
    storageBucket: 'video-plus-256c2.appspot.com',
    iosClientId: '234885058276-6m2kiru3o7rflqk1h5p086r1h9p02g65.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.videoPlus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB_ou5LZg182ULEgWje1F5pRLGxwq4Kixg",
    authDomain: "video-plus-c9d15.firebaseapp.com",
    projectId: "video-plus-c9d15",
    storageBucket: "video-plus-c9d15.appspot.com",
    messagingSenderId: "1017332431258",
    appId: "1:1017332431258:web:860807dd8f7c561d3d2223",
    measurementId: "G-LLSTJ7RRWD");
}
